<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RestorePackagesPath>$(BaseIntermediateOutputPath)packages</RestorePackagesPath>
    <RestoreAdditionalProjectSources>$(MSBuildThisFileDirectory)..\..\Jewelry.EditingSystem\bin\Release</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jewelry.EditingSystem" Version="3.0.1" />
  </ItemGroup>
</Project>
